
--select query run this first 
--SELECT
--    TRANSACTIONNO,
--    PURCHASE_DATE,
--    PRODUCTNO,
--    PRODUCTNAME,
--    PRICE,
--    QUANTITY,
--    CUSTOMERNO,
--    COUNTRY
--FROM
--    ECOMMERCE
--WHERE
--    TRANSACTIONNO = 'VARCHAR2(50)';

--My queries 


--  1

Select sum(QUANTITY) as TotalProductsSold FROM
ECOMMERCE 
WHERE PURCHASE_DATE >='2019-02-01'and 
PURCHASE_DATE<'2019-03-01'; 


-- 2 

SELECT SUBSTR(PURCHASE_DATE,1,4) as "YEAR" ,
sum(PRICE*QUANTITY) as TotalSalesAmount 
from ECOMMERCE
group by SUBSTR(PURCHASE_DATE,1,4); 
         

-- 3 

Select PRODUCTNO,SUBSTR(PURCHASE_DATE,6,2) as "Month",
sum(PRICE*QUANTITY) as TOTAL_SALES_AMOUNT from ECOMMERCE
where SUBSTR(PURCHASE_DATE,1,4)='2019' 
group by PRODUCTNO,SUBSTR(PURCHASE_DATE,6,2);
                         

-- 4

select COUNTRY,Count(Distinct(CUSTOMERNO)) as CUSTOMER_COUNT
from ECOMMERCE 
Group By COUNTRY order by COUNTRY asc ; 


-- 5

WITH CTE AS (
  	SELECT 
    	PRODUCTNAME, 
    	Extract(YEAR From To_DATE("PURCHASE_DATE", 'YYYY-MM-DD')) AS SALES_YEAR
  	FROM ECOMMERCE
	)
	SELECT 
  	Distinct(PRODUCTNAME) AS UniqueProductName,
  	SALES_YEAR
	FROM CTE
	GROUP BY SALES_YEAR, PRODUCTNAME
	ORDER BY SALES_YEAR asc;

